'use client';
import "./globals.css"
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { ThemeProvider } from "next-themes";
import { Inter } from "next/font/google";
import messagesEn from "../../messages/en.json";
import messagesEs from "../../messages/es.json";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Moontlan",
  description: "Generated by create next app",
  icons: {
    icon: "https://cdn.icon-icons.com/icons2/195/PNG/256/OS_Linux_23399.png",
  },
};

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "es" }];
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}) {
  let messages;

  if (params.locale === "en") {
    messages = messagesEn;
  } else if (params.locale === "es") {
    messages = messagesEs;
  } else {
    notFound();
  }

  return (
    <html lang={params.locale}>
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href={metadata.icons.icon}/>
        {/* Other metadata and head elements */}
      </head>
      <body className={inter.className}>
        <NextIntlClientProvider locale={params.locale} messages={messages}>
          <ThemeProvider defaultTheme="dark" attribute="class">
          <main className="dark:bg-p1 bg-gray-300 min-h-screen flex items-center justify-center relative text-white">
          <section className="z-50 opacity-[0.03] bg-back fixed inset-0 overflow-hidden pointer-events-none"></section>
            {children}
          </main>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

