'use client';
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import messagesEn from "../../messages/en.json";
import messagesEs from "../../messages/es.json";
import { ThemeProvider } from "next-themes";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Moontlan",
  description: "Generated by create next app",
  icons: {
    icon: "https://cdn.icon-icons.com/icons2/195/PNG/256/OS_Linux_23399.png",
  },
};

const inter = Inter({ subsets: ["latin"] });

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "es" }];
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}) {
  let messages;

  if (params.locale === "en") {
    messages = messagesEn;
  } else if (params.locale === "es") {
    messages = messagesEs;
  } else {
    notFound();
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextIntlClientProvider locale={params.locale} messages={messages}>
          <ThemeProvider defaultTheme="black" attribute="class">
            {children}
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
